### ISSUE TITLE
Happy Birthday Code for Poznan! 16.10

### ISSUE THREAD

**Issue by OtisRed** [CodeForPoznan/Community#10]
Venue: Piwna Stopa

1) create mailing list (23 people)

**Comment by w1stler** [comment]
I will take care of it. Friend's of mine owns this place so I should be able to get some discounts. ;-)

**Comment by w1stler** [comment]
To do: establish the list of guests.

**Comment by magul** [comment]
@w1stler have You spoke with Piwna Stopa?
