### ISSUE TITLE
Gotta get more room 

### ISSUE THREAD

**Issue by OtisRed** [CodeForPoznan/Community#11]
Since we have started there are more and more people coming to the meetings so it comes to a point when we need to consider having more space to fit everybody in. Suggestions? Ideas?

**Comment by OtisRed** [comment]
I can ask on the university if we cannot get some place in our new building?

**Comment by magul** [comment]
You can if You want, but make it non-binding

**Comment by w1stler** [comment]
What about the space in STX Next's basement? Seems like it suits us.

**Comment by magul** [comment]
@w1stler it looks, that we fit there for now, but if we will maintain growth rate we will need to look for new place in 2-3 weeks. :)

**Comment by w1stler** [comment]
Closing. I don't presume that we will move meetings to another location till April.

**Comment by magul** [comment]
What will be in April?

**Comment by w1stler** [comment]
Moving to new location.

**Comment by magul** [comment]
You mean STX or CfP?

**Comment by w1stler** [comment]
I ment STX. From April we won't be able to meet in basement.
