### ISSUE TITLE
Feedback loops

### ISSUE THREAD

**Issue by OtisRed** [CodeForPoznan/Community#12]
It would be useful to collect some feedback on the organization and activities we do. The idea is to run ongoing open-ended google survey, which contains questions about:
1) What did you like, while working on CodeForPoznań projects?
2) What did you dislike, about it?
3) Any other comments?
4) Would you like us to keep you in the loop [e-mail base]

**Comment by OtisRed** [comment]
https://goo.gl/forms/6e2xGmJq3EPbOxbj1

**Comment by w1stler** [comment]
I will create task to gather emails for every person in the community.

**Comment by OtisRed** [comment]
Cleaning spree!
