### ISSUE TITLE
Panel: volunteer tales and stories. No. 1

### ISSUE THREAD

**Issue by OtisRed** [CodeForPoznan/Community#14]
Panels: 
Last time in Bario @w1stler brought up the idea to introduce "panels" as the organizing tool for the hacknights. The concept is to have organized time-limited meeting focused on particular subject that takes place in parallel to regular work so that anyone in the group can choose if he/she wants to participate or develop the app.

Volunteer tales and stories
I thought that while developing the app for volunteers it could be a good idea to actually meet some of them on the way and hear what they have to say. It may help the team to understand them better as well as their drive to help others. Also seeing the endpoint might help developers to realize the real-life meaning of the work done during the hacknights. 

No 1: I have a friend who has been volunteer for (I think) four years in Hospicjum Palium. I can invite her to the hacknight.

**Comment by magul** [comment]
Inviting volunteers can make impact in few other areas - we can for example use them for testing volontulo, trying to understand how they would use it, we can also make them our advocates (in the sense of CfP and volontulo).

We will talk about it in nearest hacknight.

**Comment by OtisRed** [comment]
I'm in Cracow now so unfortunetely ain't gonna be there tomorrow. However (to bring my voice to the table during tomorrow's discussion) I propose to give the prospect guest at least 15-20 minutes of uninterrupted time for telling their story just as they see fit to tell about "their experiences as a volunteer". Sometimes it is really important to hear what someone wants to say on their own before asking them what we want to hear from them.

Also let me know if I shall arrange for Magda visiting us next week (or later)

**Comment by magul** [comment]
There's no hurry, se we can deffered this discussion till next week.

**Comment by OtisRed** [comment]
Cleaning spree
