### ISSUE TITLE
Uregulowanie wykorzystywania wizerunku uczestników Hacknightu

### ISSUE THREAD

**Issue by danutaj23** [CodeForPoznan/Community#22]
Wydaje mi się, że każdy nowy uczestnik Hacknightu powinien zostać poinformowany (w trakcie onboardingu?), że w trakcie Hacknightu mogą być wykonywane zdjęcia, a uczestnicy przychodząc na spotkanie wyrażają zgodę na wykorzystanie wizerunku w mediach społecznościowych oraz w prezentacjach promujących CfP.

**Comment by OtisRed** [comment]
Słusznie! Nie zwróciliśmy na to wcześniej uwagi, ale masz rację :) Trzeba by to uporządkować w instrukcji "getting_to_know_us.md", żeby to był jeden punktów do przejścia w trakcie wprowadzania nowej osoby do grupy.

**Comment by magul** [comment]
Done in #23
