### ISSUE TITLE
The aim of foundation [§8]

### ISSUE THREAD

**Issue by OtisRed** [CodeForPoznan/Community#30]
**The task:** spell the aim of the foundation in the §8

**Description:** The aim should some kind of "definite state" localized in the future and should not be the activity of accomplishing it. E.g. that refers to the difference betweeen "poprawiać" (continuous action) and "poprawić" (definite state) exemplify this issue.

**Extras:** For further discussion see [this](https://github.com/CodeForPoznan/Community/pull/1/files)

**Comment by OtisRed** [comment]
Propozycja z dyskusji:
Celami Fundacji są:
1. tworzenie nowych rozwiązań technologicznych oraz wsparcie w ich rozpowszechnianiu i wdrażaniu,
2. edukowanie w zakresie zarządzania, tworzenia i wdrażania projektów informatycznych, 
3. promowanie idei wytwarzania otwartego oprogramowania,
na rzecz społeczności lokalnych i podmiotów, realizujących zadania społecznie użyteczne, odpowiadając na realne problemy społeczne, facylitując aktywizm lokalny oraz promując odpowiedzialność za dobro wspólne w praktyce społecznej i gospodarczej.

**Comment by magul** [comment]
Done in https://github.com/CodeForPoznan/Community/pull/27/commits/614300f225a7ee28b2ad26cb181a9999d5dd0192
