### ISSUE TITLE
Composition of the board [§23]

### ISSUE THREAD

**Issue by OtisRed** [CodeForPoznan/Community#35]
**Task:** There is a question of how the board should look like from the perspective of "normal management". There are few aspects in question:
1) What should be the competence of president?
2) What should be the competence of the board member?
3) What the "normal management" should be?

**Description:**
![zarzad](https://user-images.githubusercontent.com/28675024/33962005-5b38b042-e050-11e7-9f89-fec75c0077ee.png)

**Comment by w1stler** [comment]
IMO we can leave it as it is, I mean described duties within normal management. and:

- 1 president
- 1 vice-president
- board member - is it necessary?

OR

- 1 president
- 2 (or more) board members

As we spoke last week, we can agree, that at this point we do not have to write everything in details - that can be changed easily.

**Comment by OtisRed** [comment]
@w1stler All the people in the board are "board members". President and vice-president are the function assigned to board members. Ergo every president is a board member but not every board member is a president. So the board of president and vice-president has two board members.
