### ISSUE TITLE
Public collections [§13]

### ISSUE THREAD

**Issue by OtisRed** [CodeForPoznan/Community#36]
**Task:** decide whether to keep "public collections" notion in §13 2. c)
**Description:**
![public collections](https://user-images.githubusercontent.com/28675024/34219342-289f158e-e5b1-11e7-881f-9ced2f65d04a.png)

**Comment by OtisRed** [comment]
If you accept my interpretation there is nothing more to do here

**Comment by w1stler** [comment]
Jest też coś takiego, jak darowizna rzeczowa - więc IMO te dary do wywalenia.
