### ISSUE TITLE
[TBD] Right to use of personal portrayal - doc

### ISSUE THREAD

**Issue by w1stler** [CodeForPoznan/Community#45]
1. Prepare document related to right to use of personal portrayal of people coming to our events (hacknights, workshops, etc.) for every person to sign (or not). 
1. Related materials - social media pages, webpage, promotional materials. 
1. To be done after creating foundation?

**Comment by w1stler** [comment]
@magul , @OtisRed - we should discuss that matter.

**Comment by OtisRed** [comment]
I've moved it to issue in v3 repository - 419 I think. Cleaning spree
