### ISSUE TITLE
Darowizny w kryptowalutach

### ISSUE THREAD

**Issue by danutaj23** [CodeForPoznan/Community#48]
Czy Fundacja mogłaby przyjmować darowizny w kryptowalutach? Zapewne samo rozliczanie kryptowalut może być kłopotliwe, ale gdyby zrobić to tak, jak [Stowarzyszenie Otwarte Klatki](https://www.otwarteklatki.pl/bitcoin-charytatywnie-pomoz-zwierzetom-dzieki-bitcoinowi/), to Fundacja finalnie otrzymywałaby darowiznę w złotówkach. Może jest do ogarnięcia? :-)

**Comment by danutaj23** [comment]
Jeśli dobrze kojarzę, to kryptowaluty zgodnie z orzecznictwem sądowo - administracyjnym, są kwalifikowane jako prawa majątkowe. Prawa majątkowe, zgodnie z art. 16 ustawy o fundacjach, są wolne od podatku od spadków i darowizn. 

Zapewne taką darowiznę trzeba jakoś ująć w księgach i ją wycenić, więc Stowarzyszenie Otwarte Klatki zastosowało takie rozwiązanie, że każda darowizna w kryptowalucie jest automatycznie sprzedawana na giełdzie, a uzyskane ze sprzedaży środki są przekazywane na konto bankowe. 

W [statucie](https://www.otwarteklatki.pl/statut/ ) nie wspomnieli nic o kryptowalutach.

> § 49
> Majątek Stowarzyszenia powstaje
> 1. z dotacji, grantów europejskich,
> 2. z darowizn, spadków, zapisów,
> 3. z dochodów z własnej działalności statutowej,
> 4. z dotacji i ofiarności publicznej.
> 5. ze składek członkowskich
> 6. z dochodów z działalności gospodarczej
> 
> § 50
> Stowarzyszenie prowadzi gospodarkę pieniężną zgodnie z obowiązującymi przepisami.
>

**Comment by OtisRed** [comment]
Cleaning spree!
