### ISSUE TITLE
Create Google Slides master theme

### ISSUE THREAD

**Issue by w1stler** [CodeForPoznan/Community#64]
- match with the current CI (placed in Community/logo)
- upload it to hello@codeforpoznan's gmail account (to be reused and shared with others)

**Comment by magul** [comment]
@kaczynska

**Comment by w1stler** [comment]
Initial draft: https://docs.google.com/presentation/d/1-C19c5J2Xk0VzBKL7bDCrWGTB2FEgDcUXo5sLI2EygE/edit?usp=sharing

**Comment by OtisRed** [comment]
It's been done - old enough to close it - cleaning spree
