### ISSUE TITLE
Slack automatic invite

### ISSUE THREAD

**Issue by juliaanholcer** [CodeForPoznan/Community#69]
I don't know whether we still want to have the possibility to send slack invitation automatically but if so, it is a task that needs to be done :-)

https://github.com/rauchg/slackin

**Comment by magul** [comment]
@OtisRed read discovered a way to self-invite to slack using their (Slack) internal resource so I believe Slackin should be depraceted.

**Comment by magul** [comment]
We already have a Slack auto invitation (provided by Slack itself). We can close this ticket now.
