### ISSUE TITLE
Add info about description for issues and PRs to technical onboarding

### ISSUE THREAD

**Issue by Loczi94** [CodeForPoznan/Community#71]
To do:
1. Add document with info about descriptions for issues and PRs to technical_onboarding.
2. Describe good practices and add some examples of descriptions/comments.
Note:
It is a good practice to add detailed description for each issue so everyone knows what is it about. We should also add comments to PRs with expected behaviour and/or description of how to test it.

**Comment by OtisRed** [comment]
I think it was done. If not - it'll come back
