### ISSUE TITLE
Publicznie dostępny kalendarz wydarzeń

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/Community#80]
Do przegadania - temat przyniósł @ad-m, brakuje troche miejsca, gdzie można sprawdzić co i o której się wydarza. Dodatkowo można pomyśleć o integracji tego z cfp_v3.

**Comment by ad-m** [comment]
Wystarczy do tego stworzyć kalendarz Google, nadać odpowiednim osobom z każdego projektu prawa dostepu i powinno się kręcić, póki jeden projekt nie przytłoczy swoją aktywnością kalendarza.

**Comment by ad-m** [comment]
Kalendarze Google można innym udostępniać do edycji, a także publikować jako strona / do dodania przez każdego.

**Comment by ad-m** [comment]
Podobno Code For Poznań udostępniło publicznie kalendarz (w końcu!) googlowski i podobno można się subskrybować tutaj: https://calendar.google.com/calendar/u/0/embed?src=hello@codeforpoznan.pl&ctz=Europe/Warsaw

Zgłoszenie do zamknięcia?

**Comment by magul** [comment]
Zamykam. Inną sprawą jest umieszczenie kalendarza w odpowiednim miejscu na naszej stronie, ale na to będzie ticket w repo ze stroną.
